image: bioconductor/release_core2:latest

pipelines:
  default:
    - step:
        script:
          - apt-get update -qq && apt-get -y --no-install-recommends install subversion libxml2-dev libcairo2-dev   libsqlite-dev libmariadbd-dev libmariadb-client-lgpl-dev libpq-dev libssh2-1-dev 
          - cd /opt/atlassian/pipelines/agent/build
          - Rscript -e 'install.packages("devtools")'
          - Rscript -e "devtools::install_bitbucket('tanaylab/shaman@default', vignette = TRUE,    repos=c(getOption('repos'), 'https://tanaylab.bitbucket.io/repo'))"