// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// shaman_hic_matrix_shuffler_cpp
int shaman_hic_matrix_shuffler_cpp(Rcpp::DataFrame& raw_contacts, std::string shuf_contacts, int shuffle_factor, int proposal_from_contacts, double proposal_iterations_d, int dist_resolution, int decay_smooth, int decay_regularization, double proposal_correction_factor_d, int max_dist, int min_dist, int grid_switch_bin_dist, int grid_x_min_bin, int grid_x_max_bin, int grid_x_increase, int grid_x_increase_iter, int input_symmetric_mat, int output_symmetric_mat);
RcppExport SEXP _shaman_shaman_hic_matrix_shuffler_cpp(SEXP raw_contactsSEXP, SEXP shuf_contactsSEXP, SEXP shuffle_factorSEXP, SEXP proposal_from_contactsSEXP, SEXP proposal_iterations_dSEXP, SEXP dist_resolutionSEXP, SEXP decay_smoothSEXP, SEXP decay_regularizationSEXP, SEXP proposal_correction_factor_dSEXP, SEXP max_distSEXP, SEXP min_distSEXP, SEXP grid_switch_bin_distSEXP, SEXP grid_x_min_binSEXP, SEXP grid_x_max_binSEXP, SEXP grid_x_increaseSEXP, SEXP grid_x_increase_iterSEXP, SEXP input_symmetric_matSEXP, SEXP output_symmetric_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame& >::type raw_contacts(raw_contactsSEXP);
    Rcpp::traits::input_parameter< std::string >::type shuf_contacts(shuf_contactsSEXP);
    Rcpp::traits::input_parameter< int >::type shuffle_factor(shuffle_factorSEXP);
    Rcpp::traits::input_parameter< int >::type proposal_from_contacts(proposal_from_contactsSEXP);
    Rcpp::traits::input_parameter< double >::type proposal_iterations_d(proposal_iterations_dSEXP);
    Rcpp::traits::input_parameter< int >::type dist_resolution(dist_resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type decay_smooth(decay_smoothSEXP);
    Rcpp::traits::input_parameter< int >::type decay_regularization(decay_regularizationSEXP);
    Rcpp::traits::input_parameter< double >::type proposal_correction_factor_d(proposal_correction_factor_dSEXP);
    Rcpp::traits::input_parameter< int >::type max_dist(max_distSEXP);
    Rcpp::traits::input_parameter< int >::type min_dist(min_distSEXP);
    Rcpp::traits::input_parameter< int >::type grid_switch_bin_dist(grid_switch_bin_distSEXP);
    Rcpp::traits::input_parameter< int >::type grid_x_min_bin(grid_x_min_binSEXP);
    Rcpp::traits::input_parameter< int >::type grid_x_max_bin(grid_x_max_binSEXP);
    Rcpp::traits::input_parameter< int >::type grid_x_increase(grid_x_increaseSEXP);
    Rcpp::traits::input_parameter< int >::type grid_x_increase_iter(grid_x_increase_iterSEXP);
    Rcpp::traits::input_parameter< int >::type input_symmetric_mat(input_symmetric_matSEXP);
    Rcpp::traits::input_parameter< int >::type output_symmetric_mat(output_symmetric_matSEXP);
    rcpp_result_gen = Rcpp::wrap(shaman_hic_matrix_shuffler_cpp(raw_contacts, shuf_contacts, shuffle_factor, proposal_from_contacts, proposal_iterations_d, dist_resolution, decay_smooth, decay_regularization, proposal_correction_factor_d, max_dist, min_dist, grid_switch_bin_dist, grid_x_min_bin, grid_x_max_bin, grid_x_increase, grid_x_increase_iter, input_symmetric_mat, output_symmetric_mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_shaman_shaman_hic_matrix_shuffler_cpp", (DL_FUNC) &_shaman_shaman_hic_matrix_shuffler_cpp, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_shaman(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
